config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      patch :accepted, :declined
    end
  end
  
  resources :chatrooms, only: [:show, :index]
  get "/dashboard", to: "dashboards#dashboard"
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :flat_type, presence: true, inclusion: { in: %w(flat room) }
  validates :number_of_rooms, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_month, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :separation_allowed, presence: true, numericality: { only_integer: true, greater_than: 0 }
  has_many_attached :photos, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  # before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
    if search_params[:location].present?
      @flats = @flats.where("location ILIKE ?", "%#{search_params[:location]}%")
    end

    if search_params[:separation_allowed].present?
      @flats = @flats.where("separation_allowed <= ?", "#{search_params[:separation_allowed]}")
    end

    if search_params[:dates].present?
      dates = search_params[:dates].split(" to ")
      @start_at = Date.parse(dates[0])
      @end_at = Date.parse(dates[1])
      query = <<-SQL
      (
        (
          start_date >= :start_at
          AND
          start_date <= :end_at
        )
        OR
        (
          end_date >= :start_at
          AND
          end_date <= :end_at
        )
      )
      SQL
      conflicting_bookings = Booking.where(confirmed: "confirmed")
        .where(query, start_at: @start_at, end_at: @end_at)
      flat_ids_with_conflicting_bookings = conflicting_bookings.pluck(:flat_id)
      @flats = @flats.where.not(id: flat_ids_with_conflicting_bookings)
    end

    @flats = @flats.geocoded

    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    if params[:dates]
      @dates = params[:dates].split
      @start_date = Date.parse(@dates[0]).strftime("%e %B %Y")
      @end_date = Date.parse(@dates[2]).strftime("%e %B %Y")
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to dashboard_path
  end

  private

  def search_params
    params.require(:search).permit(:separation_allowed, :location, :dates)
  end

  def flat_params
    params.require(:flat).permit(:name, :description, :location, :flat_type, :number_of_rooms, :price_per_month, :separation_allowed, photos: [])
  end
end

app/views/flats/_form.html.erb
<div class = new_flat>

</div>
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :flat_type, collection: ["flat", "room"] %>
  <%= f.input :number_of_rooms %>
  <%= f.input :price_per_month %>
  <%= f.input :separation_allowed, label: "Handshakes 🤝" %>
<!--   Single image preview
 -->  <%#= f.input :photos, as: :file, input_html: { multiple: true, class: 'hidden', class: 'd-none', id: 'photo-input' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
  <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'hidden', class: 'd-none', id: 'photo-input', onChange: "imagesPreview(this, 'div.gallery')" }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo', direct_upload: true %>
  <%#= image_tag "", width: 150, class: "hidden", id: "photo-preview" %>
  <div class="gallery"></div>
  <%= f.button :submit, 'Submit'%>
<% end %>
<script>
    // Multiple images preview in browser
    var imagesPreview = function(input, placeToInsertImagePreview) {
        if (input.files) {
            var filesAmount = input.files.length;
            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();
                reader.onload = function(event) {
                    $($.parseHTML('<img class="preview-img">')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                }
                reader.readAsDataURL(input.files[i]);
            }
        }
    };
  </script>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/edit.html.erb
<div class="flex-container">
   <div class="flex-item container">
    <div class="new_flat">
      <h1>Make any changes you like</h1>
    </div>
    <%= render "form", flat: @flat %>
  </div>
  <div class="flex-item form-image">
    <%= image_tag "new_flat.jpg" %>
  </div>
</div>

app/views/flats/index.html.erb
<br>
<div class="container-fluid d-flex">
    <div class="cards">
      <% @flats.each do |flat| %>
      <%= link_to flat_path(flat, dates: params[:search][:dates]) do %>
         <div class="card-flat">
            <% if flat.photos.attached? %>
              <%= cl_image_tag flat.photos.first.key %>
            <% else %>
              <img src="https://www.solidbackgrounds.com/images/3840x2160/3840x2160-dark-gray-solid-color-background.jpg">
            <% end %>
              <div class="card-flat-infos">
                <div>
                  <div class="card-flat-name">
                    <h3><%= flat.name.capitalize %></h3>
                  </div>
                  <p>
                  <%= "#{flat.flat_type.capitalize} · " %>
                  <%= flat.number_of_rooms %> <%= "room".pluralize(flat.number_of_rooms).capitalize %> ·
                  </p>
                  <div>
                  <p><%= "#{flat.separation_allowed} ° separation" %></p>
                  </div>
                  <h2 class="card-flat-pricing"><%= "#{flat.price_per_month}€/month" %></h2>
                </div>
                <% if flat.user.facebook_picture_url%>
                  <%= image_tag flat.user.facebook_picture_url, class: "card-flat-user avatar-bordered" %>
                <% elsif flat.user.photo.attached? %>
                  <%= cl_image_tag flat.user.photo.key, width: 40, height: 40, crop: :fill, class: "card-flat-user avatar-bordered" %>
                <% else %>
                  <span class="iconify card-flat-user avatar" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
                <% end %>
              </div>
          </div>
      <% end %>
    <% end %>
</div>




  <div class="col-6">
    <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="flex-container">
   <div class="flex-item container">
    <div class="new_flat">
      <h1>Let’s set up your flat</h1>
        <h2 style= "margin-bottom: 20px"> Please fill out the following form 📝</h2>
    </div>
    <%= render "form", flat: @flat %>
  </div>
  <div class="flex-item form-image">
    <%= image_tag "new_flat.jpg" %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container pt-4">


  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2> <%= @flat.name.capitalize %> </h2>
        <p> 📍 <%= @flat.location.capitalize %></p>
      </div>
    </div>
    <div class="row card-apartment-images">
      <div class="col-6">
        <% @flat.photos.take(1).each do |photo| %>
          <div class="card-apartment">
            <%= cl_image_tag photo.key, class: ""%>
          </div>
        <% end %>

      </div>


      <div class="col-6">
        <div class="img-grid">
            <% @flat.photos.drop(1).each do |photo| %>
              <div class="card-category">
                <%= cl_image_tag photo.key, class: "img-grid-item"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>


    <div class="row">
      <div class="col-9">
        <div class="d-flex justify-content-between">
          <div class="d-flex align-items-center">🏡 <%= @flat.flat_type.capitalize %> 🚪 <%= @flat.number_of_rooms %> <%= "room".pluralize(@flat.number_of_rooms).capitalize %> 🔑 <%= @flat.user.first_name.capitalize %> <% if current_user != @flat.user %> 🔗 Frederike <% end %></div>

          <div class="card-apartment-infos">
              <% if current_user != @flat.user %>
                <% if current_user.facebook_picture_url%>
                  <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% elsif current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% else %>
                  <span class="iconify" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
                <% end %>
                <p class="arrow-avatar"> &#8596; </p>
                <img class="avatar-bordered avatar-grey" alt="avatar-bordered-grey" src="<%= image_path 'frederike.png' %>" />  <p class="arrow-avatar"> &#8596; </p>

                <% if @flat.user.facebook_picture_url%>
                  <%= image_tag @flat.user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% elsif @flat.user.photo.attached? %>
                  <%= cl_image_tag @flat.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% else %>
                  <span class="iconify" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
                <% end %>
              <% end %>

            </div>
          </div>

        <div class="textbox-lg">
          <h2>🗒 Description</h2>
          <div class="flat-description-box mt-4">
            <p><%= @flat.description %></p>
          </div>
        </div>
      </div>

      <div class="col-3">
        <div class="textbox-sm">
          <div class="avatar-bordered" id="avatar-right">
            <% if @flat.user.facebook_picture_url%>
              <%= image_tag @flat.user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% elsif @flat.user.photo.attached? %>
              <%= cl_image_tag @flat.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <span class="iconify" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
            <% end %>
          </div>

          <h3>Price</h3>
          <p><%= @flat.price_per_month %>€/month</p>
          <h3>Handshakes</h3>
          <p><% @flat.separation_allowed.times do  %> 🤝 <% end %></p>
          <h3>Rental Period</h3>
          <p> <%= @start_date %> - <%= @end_date %> </p>
          <div class="d-flex justify-content-center">
            <%= link_to "Book 🤝", new_flat_booking_path(@flat, :dates => params[:dates]), class:"btn btn-rounded", data: {turbolinks: false} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>