config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      patch :accepted, :declined
    end
  end
  
  resources :chatrooms, only: [:show, :index]
  get "/dashboard", to: "dashboards#dashboard"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <h2> <%= link_to "Flats 4 Friends", root_path, data: { turbolinks: false } %> </h2>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Add flat", new_flat_path, class: "btn btn-rounded" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.facebook_picture_url%>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", style: "cursor: pointer", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% elsif current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", style: "cursor: pointer", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "https://api.iconify.design/carbon:user-avatar-filled-alt.svg", class: "avatar dropdown-toggle", style: "cursor: pointer", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="dropdown-item font-weight-bold"><%= "Hi #{current_user.first_name}!" %></div>
            <%= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
            <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Manage Listings", dashboard_path, class: "dropdown-item" %>
            <%= link_to "User Account", edit_user_registration_path , class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex">
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>