config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      patch :accepted, :declined
    end
  end
  
  resources :chatrooms, only: [:show, :index]
  get "/dashboard", to: "dashboards#dashboard"
end

app/views/pages/_search.html.erb
<% location = params[:search][:location] if !params[:search].nil? %>
<% separation_allowed = params[:search][:separation_allowed] if !params[:search].nil? %>

  <%= simple_form_for :search, url: flats_path, method: "get" do |f| %>
  <div class = "d-flex form-inline search-input-container justify-content-center align-items-center" >

    <!-- <div class="hover-bar"> -->
      <%= f.input :separation_allowed, required: false, placeholder: "How close to the host?", label: "Handshakes 🤝", wrapper_html: { class: "search-input-item hover-message", data: { tooltip: "How many friends"} }, input_html: { value: location, data: { tooltip: "How many friends"}, style: "cursor: pointer" } %>

    <!-- </div> -->

    <%= f.input :location, required: true, label: "City", placeholder: "Where to?", wrapper_html: {class: "search-input-item"}, input_html: {  value: separation_allowed, style: "cursor: pointer" }, id: "city-input" %>

    <%= f.input :dates, required: false, placeholder: "Add some dates", wrapper_html: {class: "search-input-item"}, input_html: { class: "datepicker-range" }, label: "Check-in/Check-out" %>

    <%= f.button :submit, "Search", class: "btn btn-rounded" %>

  </div>
<% end %>

app/views/pages/home.html.erb
  <%= render"search" %>
<div class="tooltip">Hover over me
  <span class="tooltiptext">Tooltip text</span>
</div>

<div class = "textbox">
  <h1>The Social Network of Living</h1>
  <br>
  <h3>We connect friends of friends to create a flat search experience that is trustworthy, fast and convenient.</h3>
</div>

  <div class="animation-box d-flex align-items-center">
    <div style="position: relative;">
      <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
      <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_l2AAOR.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
    </div>
  </div>

<div class="cards">
  <div class="card">
    <h2 class="text-center">🤝<br><br>What do we do?</h2>
    <p> F4F allows for a comprehensive overview of the flats on offer in your network and facilitates a trustful relationship with the person renting out the appartment.</p>
  </div>
  <div class="card">
    <h2 class="text-center">🤔<br><br>Why do we do it?</h2>
    <p>We became so frustrated with the experience of finding a flat and the untapped potential within our own personal network that we created a way to make the search more trustful and effortless ourselves.</p>
  </div>
  <div class="card">
    <h2 class="text-center">🔍<br><br>How do we do it?</h2>
    <p>Did you know? You know any person in the world through only 6 people. Our handshake feature shows you the number of people it would take to make an intro between you and the flat owner in real life.</p>
  </div>
</div>