config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      patch :accepted, :declined
    end
  end
  
  resources :chatrooms, only: [:show, :index]
  get "/dashboard", to: "dashboards#dashboard"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @user = current_user
    @bookings_as_owner = Booking.joins(:flat).where(flats: { user_id: @user.id })
    @flats = @user.flats
  end
end

app/views/dashboards/_avatar.html.erb
<% if booking.user.facebook_picture_url%>
  <%= image_tag booking.user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
<% elsif booking.user.photo.attached? %>
  <%= cl_image_tag booking.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
<% else %>
  <span class="iconify" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
<% end %>

app/views/dashboards/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 card-dashboard">
      <h3 class="card-dashboard-title">Bookings</h3>
        <% @bookings_as_owner.each do |booking| %>
            <div class="d-flex justify-content-between card-dashboard-item">
          <%= link_to booking_path(booking) do %>
              <div class="d-flex">
                <% if booking.user.facebook_picture_url%>
                  <%= image_tag booking.user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% elsif booking.user.photo.attached? %>
                  <%= cl_image_tag booking.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                <% else %>
                  <span class="iconify" data-inline="false" data-icon="bi:person-circle" style="font-size: 40px;"></span>
                <% end %>
                <div class="booking-info">
                  <span> Request · <%= booking.user.first_name%> · <%= booking.confirmed %></span>
                  <p><%= booking.start_date %> - <%= booking.end_date %>  · <%= booking.flat.name %></p>
                </div>
              </div>
              <div class="d-flex booking-actions">
                <% if booking.confirmed == "pending" %>
                  <%= link_to "Respond", chatroom_path(booking.id), class: "action-button respond-button"%>
                  <%= link_to "Accept", accepted_booking_path(booking.id), method: :patch, class: "action-button accept-button" %>
                  <%= link_to "Decline", declined_booking_path(booking.id), method: :patch, class: "action-button decline-button" %>
                <% end %>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 card-dashboard">
      <div class="d-flex justify-content-between">
      <h3 class="card-dashboard-title">Flats</h3>
      <div>
        <%= link_to "Add flat", new_flat_path, class: "btn add-button" %>
      </div>
      </div>
        <% @flats.each do |flat| %>
          <%= link_to flat_path(flat) do %>
            <div class="d-flex justify-content-between card-dashboard-item">
              <div class="d-flex">
                <% if flat.photos.attached? %>
                  <%= cl_image_tag flat.photos.first.key, width: 40, height: 40, crop: :fill, class: "rounded"%>
                <% else %>
                  <span class="iconify" data-inline="false" data-icon="bi:card-image" style="font-size: 40px;"></span>
                <% end %>
                <div class="booking-info">
                  <span><%= flat.name %></span>
                  <p><%= flat.flat_type.capitalize %> · <%= flat.location.capitalize %></p>
                </div>
              </div>
              <div class="d-flex booking-actions">
                  <%= link_to "Delete", flat_path(flat.id), method: :delete, data: { confirm: "Are you sure?"}, class: "action-button decline-button"%>
                  <%= link_to "Edit", edit_flat_path(flat.id), class: "action-button respond-button" %>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>